- block:
  - name: Add docker engine GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Add docker engine repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      filename: docker_ce
      state: present

  - name: Update repository index
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Docker CE
    apt:
      name: docker-ce
      state: present

  - name: Add user to docker group
    user:
      name: "{{docker_user}}"
      append: yes
      groups: docker
