---
- hosts: all
  become: True
  # vars_files:
  #   - group_vars/vault.yml

  pre_tasks:
    - debug: msg='Starting docker setup playbook'

  post_tasks:
    - debug: msg='Finished docker setup playbook'

  roles:
    - { role: debian_base }
    - { role: docker_debian, docker_user: "{{ansible_user}}" }
    - { role: drone }
