- block:
  - name: Update repositories
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install base packages
    apt:
      name: "{{item}}"
    with_items:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - curl
      - gnupg2
      - build-essential
      - git
      - vim
      - htop
      - lsof
      - dstat
      - strace
      - tmux
